steps:
  build-image:
    image: coralhl/woodpecker-buildx-plugin
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: coralhl/dagu
      platforms:
        - linux/amd64
        - linux/arm64
      build_args:
        - VERSION=1.14.5
      tags:
        - latest
        - ${VERSION}