steps:
  build:
    image: woodpeckerci/plugin-docker-buildx
    commands:
      - tag_name=$(cat "VERSION")
      - export tag_name=$${tag_name}
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: coralhl/dagu
      platforms:
        - linux/amd64
        - linux/arm64
      build_args:
        - VERSION: 
      tags:
      - latest
      - $tag_name