when:
  - event: [push, tag, cron, manual]

steps:
  build-image:
    image: coralhl/woodpecker-buildx-plugin
    privileged: true
    settings:
      repo: coralhl/dagu,reg.xciii.ru/coral/dagu
      platforms:
        - linux/amd64
        - linux/arm64
      build_args:
        - VERSION=1.16.0
      tags:
        - latest
        - 1.16.0
      logins:
        - registry: docker.io
          username:
            from_secret: dockerhub_username
          password:
            from_secret: dockerhub_password
        - registry: reg.xciii.ru
          username:
            from_secret: reg_xciii_username
          password:
            from_secret: reg_xciii_password
