steps:
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      repo: coralhl/dagu
      platforms:
        - linux/amd64
        - linux/arm64
      build_args:
        - VERSION=${VERSION}
      tags:
        - latest
        - ${VERSION}
    commands:
      - VERSION=$(cat "VERSION")