when:
  - event: [push, tag, cron, manual]

labels:
  platform: linux/amd64

depends_on:
  - merge-manifests

steps:
  add-version:
    image: coralhl/woodpecker-skopeo-copy:latest
    privileged: true
    settings:
      source: docker://reg.xciii.ru/coral/dagu:latest
      target: docker://reg.xciii.ru/coral/dagu:1.16.0
      source-username:
        from_secret: reg_xciii_username
      source-password:
        from_secret: reg_xciii_password
      target-username:
        from_secret: reg_xciii_username
      target-password:
        from_secret: reg_xciii_password

  copy-to-dh:
    image: coralhl/woodpecker-skopeo-copy:latest
    privileged: true
    settings:
      source: docker://reg.xciii.ru/coral/dagu:latest
      target: docker://docker.io/coralhl/dagu:latest
      source-username:
        from_secret: reg_xciii_username
      source-password:
        from_secret: reg_xciii_password
      target-username:
        from_secret: dockerhub_username
      target-password:
        from_secret: dockerhub_password

  add-version-to-dh:
    image: coralhl/woodpecker-skopeo-copy:latest
    privileged: true
    settings:
      source: docker://docker.io/coralhl/dagu:latest
      target: docker://docker.io/coralhl/dagu:1.16.0
      source-username:
        from_secret: dockerhub_username
      source-password:
        from_secret: dockerhub_password
      target-username:
        from_secret: dockerhub_username
      target-password:
        from_secret: dockerhub_password