when:
  - event: [push, tag, cron, manual]

labels:
  platform: linux/amd64

depends_on:
  - build-image-amd64
  - build-image-arm64

steps:
  merge-manifests:
    image: coralhl/woodpecker-buildah:latest
    privileged: true
    settings:
      commands: [login, manifest]
      username:
        from_secret: reg_xciii_username
      password:
        from_secret: reg_xciii_password
      registry: reg.xciii.ru
      tag: reg.xciii.ru/coral/dagu:latest
      manifest-tags:
        - reg.xciii.ru/coral/dagu:amd64
        - reg.xciii.ru/coral/dagu:arm64
