name: build and publish
on:
  push:
    branches:
      - main
  workflow_dispatch:    

env:
  REGISTRY: docker.io
  IMAGE_NAME: coralhl/dagu
  IMAGE_TAG: "1.20.0"
  IMAGE_PLATFORMS: linux/amd64,linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.IMAGE_PLATFORMS }}

      - name: Build Image
        id: build_image_multiplatform
        uses: coralhl/buildah-action@main
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }}
          platforms: ${{ env.IMAGE_PLATFORMS }}
          push: true
          registry: ${{ env.REGISTRY }}
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Copy from DH to DH latest
        uses: coralhl/skopeo-action@main
        with:
          source: docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          target: docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          source_username: ${{ secrets.DOCKERHUB_USERNAME }}
          source_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          target_username: ${{ secrets.DOCKERHUB_USERNAME }}
          target_password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Copy from DH to Private Registry version
        uses: coralhl/skopeo-action@main
        with:
          source: docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          target: docker://${{ secrets.PRIV_REG }}/${{ secrets.PRIV_REG_USERNAME }}/dagu:${{ env.IMAGE_TAG }}
          source_username: ${{ secrets.DOCKERHUB_USERNAME }}
          source_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          target_username: ${{ secrets.PRIV_REG_USERNAME }}
          target_password: ${{ secrets.PRIV_REG_PASSWORD }}

      - name: Copy from DH to Private Registry latest
        uses: coralhl/skopeo-action@main
        with:
          source: docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          target: docker://${{ secrets.PRIV_REG }}/${{ secrets.PRIV_REG_USERNAME }}/dagu:latest
          source_username: ${{ secrets.DOCKERHUB_USERNAME }}
          source_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          target_username: ${{ secrets.PRIV_REG_USERNAME }}
          target_password: ${{ secrets.PRIV_REG_PASSWORD }}
